### ISSUE TITLE
jenkins点击“更新中心设置 ”，404错误

### ISSUE THREAD

**Issue by jptiancai** [jenkins-zh/mirror-adapter#4]
1. 安装好插件，https://plugins.jenkins.io/localization-zh-cn
2. 重启Jenkins
3. 点击更新中心设置，报错404

**Comment by LinuxSuRen** [comment]
可以帮忙给出更详细的复现步骤吗

**Comment by LinuxSuRen** [comment]
该缺陷已经在 jenkinsci/localization-zh-cn-plugin#124 中修复。另外，上面错误应该是属于 Jenkins 简体中文插件的。
