### ISSUE TITLE
如何使用新的证书文件

### ISSUE THREAD

**Issue by belier-cn** [jenkins-zh/mirror-adapter#7]
安装了 localization-zh-cn-plugin

在插件管理页面设置了 https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json 地址

结果还是很慢，证书文件的使用没有找到配置的地方

**Comment by LinuxSuRen** [comment]
清华源和社区给出的方案没有关系。如果希望用社区的方案，请参考 Jenkins 中文社区官方论坛上的介绍https://community.jenkins-zh.cn/t/jenkins/26/。
